version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: workflow_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  mongodb:
    image: mongo:latest
    container_name: workflow_auth_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  postgres_data:
  mongodb_data:
